### ISSUE TITLE
Add more cloud testing configurations

### ISSUE THREAD

**Issue by liza-mae** [elastic/elastic-stack-testing#394]
Cloud test configurations to support: 

- [x] SaaS AWS staging 
- [x] SaaS GCP staging 
- [x] SaaS Azure staging 
- [x] ECE 
- [x] ECK 

Product test configurations 
- [x] Kibana option overrides (for functional tests)
- [x] Multiple Kibana instances 
- [x] Machine Learning enabled (for functional tests)

**Comment by liza-mae** [comment]
I have added all configurations above for ECE, SaaS and ECK.  Yay! :) 
Closing.
